#! /bin/bash
lspci | grep -q "Broadcom Corporation BCM4322"
if (( $? != 0 )); then
    echo "Wrong Broadcom chipset, exiting.."
    exit 1
fi

ping -W 2 -c 1 google.com &> /dev/null
if (( $? == 1 )); then
    echo "apt-get some internetz plix!"
    exit 1
fi

sudo apt-get install linux-headers-generic
sudo apt-get install --reinstall bcmwl-kernel-source
sudo modprobe wl
