#! /bin/bash
# Set different monitor modes

if [[ $1 == dual ]]; then
    xrandr --output LVDS-1 --mode 1280x800 --pos 0x0 --output DP-1 --mode 1920x1200 --pos 1280x0
    echo "Dual monitor set"
elif [[ $1 == single ]]; then
    xrandr --output LVDS-1 --mode 1280x800 --pos 0x0 --output DP-1 --off
    echo "Single monitor set"
fi
