#!/bin/bash

if (( $# != 2 )); then
    echo "Missing arguments"
    exit 1
fi

fromdate=$1
todate=$2

from=`echo $fromdate | awk  -F\. '{print $3$2$1}'`
to=`echo $todate | awk  -F\. '{print $3$2$1}'`

START_DATE=`date --date=$from +"%s"`
END_DATE=`date --date=$to +"%s"`

DAYS=$((($END_DATE - $START_DATE) / 86400 ))
echo $DAYS
