#! /bin/bash
echo -n "Username at remote host: "
read user
echo -n "Remote host: "
read host
echo -n "Tunnel port: "
read port
if [[ $port == "" ]]; then
    port="8080"
fi
echo "Tunneling to $user@$host at port $port.."
ssh -ND $port $user@$host
