#! /bin/bash

IP=$(curl -s ifconfig.me)
if (( $? == 1)); then
    IP=$(curl -s checkip.dyndns.com | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
    if (( $? != 0 )); then
        echo "No internet connection!"
    fi
fi
if [[ "$IP" != "" ]]; then
    echo "Current public IP: $IP"
fi
