#! /bin/bash

IP=$(curl --max-time 2 -s ifconfig.me)
if (( $? != 0)); then
    IP=$(curl --max-time 3 -s checkip.dyndns.com | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
    if (( $? != 0 )); then
        echo -e "Unable to obtain public IP adress.\nNo connection?"
        exit 1
    fi
fi
if [[ "$IP" != "" ]]; then
    echo "Public IP: $IP"
fi
